ai_provider_llmd.settings:
  type: config_object
  label: 'LLM-d settings'
  mapping:
    host:
      type: string
      label: 'LLM-d orchestrator host URL'
    api_key:
      type: string
      label: 'API key identifier for key module'
    timeout:
      type: integer
      label: 'Request timeout in seconds'
    debug:
      type: boolean
      label: 'Enable debug logging'